### ISSUE TITLE
Error from line 35 of /data/mediawiki/extensions/Wikibase/lib/WikibaseLib.entitytypes.php: Class 'Wikibase\DataModel\Entity\ItemId' not found

### ISSUE THREAD

**Issue by e-tang** [tyolab/localwiki-builder#1]
When we are initialising the wikimedia software:
```
php maintenance/install.php "Arabic Wikipedia" "admin" --pass=aaaaa
```

Error happened:
PHP 7.2.24-0ubuntu0.18.04.3 is installed.
Found ImageMagick: /usr/bin/convert. Image thumbnailing will be enabled if you enable uploads.
Found the Git version control software: /usr/bin/git.
Warning: No --scriptpath specified, using default: /wiki.
Using server URL "/wiki".
Warning: Your default directory for uploads (/data/mediawiki/all/arwiki/images/) is not checked for vulnerability to arbitrary script execution during the CLI install.
Using the intl PECL extension for Unicode normalization.
The environment has been checked. You can install MediaWiki.
[faf574545718138a5b7778f5] [no req]   Error from line 35 of /data/mediawiki/extensions/Wikibase/lib/WikibaseLib.entitytypes.php: Class 'Wikibase\DataModel\Entity\ItemId' not found
Backtrace:
#0 /data/mediawiki/extensions/Wikibase/client/includes/WikibaseClient.php(447): require()
#1 /data/mediawiki/extensions/Wikibase/client/includes/WikibaseClient.php(667): Wikibase\Client\WikibaseClient::getDefaultEntityTypes()
#2 /data/mediawiki/extensions/Wikibase/client/includes/WikibaseClient.php(740): Wikibase\Client\WikibaseClient::newInstance()
#3 /data/mediawiki/extensions/Wikibase/client/includes/Hooks/ParserClearStateHookHandler.php(22): Wikibase\Client\WikibaseClient::getDefaultInstance()
#4 /data/mediawiki/all/arwiki/includes/Hooks.php(174): Wikibase\Client\Hooks\ParserClearStateHookHandler::onParserClearState(Parser)
#5 /data/mediawiki/all/arwiki/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#6 /data/mediawiki/all/arwiki/includes/parser/Parser.php(420): Hooks::run(string, array)
#7 /data/mediawiki/all/arwiki/includes/parser/Parser.php(4774): Parser->clearState()
#8 /data/mediawiki/all/arwiki/includes/parser/Parser.php(450): Parser->startParse(Title, ParserOptions, integer, boolean)
#9 /data/mediawiki/all/arwiki/includes/cache/MessageCache.php(1243): Parser->parse(string, Title, ParserOptions, boolean)
#10 /data/mediawiki/all/arwiki/includes/Message.php(1253): MessageCache->parse(string, Title, boolean, boolean, LanguageEn)
#11 /data/mediawiki/all/arwiki/includes/Message.php(878): Message->parseText(string)
#12 /data/mediawiki/all/arwiki/includes/Message.php(931): Message->toString(string)
#13 /data/mediawiki/all/arwiki/includes/installer/CliInstaller.php(221): Message->parse()
#14 /data/mediawiki/all/arwiki/includes/installer/CliInstaller.php(204): CliInstaller->getMessageText(array)
#15 /data/mediawiki/all/arwiki/includes/installer/CliInstaller.php(240): CliInstaller->showMessage(string)
#16 /data/mediawiki/all/arwiki/includes/installer/CliInstaller.php(171): CliInstaller->showStatusMessage(Status)
#17 /data/mediawiki/all/arwiki/maintenance/install.php(129): CliInstaller->execute()
#18 /data/mediawiki/all/arwiki/maintenance/doMaintenance.php(94): CommandLineInstaller->execute()
#19 /data/mediawiki/all/arwiki/maintenance/install.php(179): require_once(string)
#20 {main}

**Comment by e-tang** [comment]
Make sure that you have created "composer.local.json" in the _mediawiki_ directory
 ```
{
	"extra": {
		"merge-plugin": {
			"include": [
				"extensions/Wikibase/composer.json",
				"extensions/Flow/composer.json"
			]
		}
	}
}

```

then
```bash
# optional, if you have run composer install before
rm -f composer.lock

composer install --no-dev
```
